### ISSUE TITLE
passenger in apache segfaulting with version 3.0.7-4

### ISSUE THREAD

**Issue by willaerk** [erikogan/passenger#11]
Hi,

I seem to be encountering a segfault when starting RHEL/CentOS 5/6 x86_64 apache
when using the passenger 3.0.7-4 RPMs.
The 3.0.7-4 then leaves a defunct PassengerHelper process behind.

Downgrading to 3.0.7-2 works fine, problem with 3.0.7-4 is easily reproducible on
standard RHEL5/6 and Centos5 x86_64.
I thought it was a real Passenger bug, but since 3.0.7-2 works fine, I'm somehow
suspecting an addition (patch) to the vanilla source.

This is what happens when I try 3.0.7-4:

<pre>
[root@puppetmaster httpd]# service httpd stop
Stopping httpd:                                            [  OK  ]

[root@puppetmaster httpd]# > /var/log/httpd/error_log 

[root@puppetmaster httpd]# rpm -qa | grep passenger
rubygem-passenger-native-3.0.7-2.el5
rubygem-passenger-native-libs-3.0.7-2.el5_1.8.5
passenger-release-3-5.el5
rubygem-passenger-3.0.7-2.el5
mod_passenger-3.0.7-2.el5

[root@puppetmaster httpd]# service httpd start
Starting httpd: [Fri Jul 29 17:43:08 2011] [warn] module passenger_module is already loaded, skipping
[Fri Jul 29 17:43:08 2011] [warn] module ssl_module is already loaded, skipping
                                                           [  OK  ]

[root@puppetmaster httpd]# cat /var/log/httpd/error_log 
[Fri Jul 29 17:43:08 2011] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Jul 29 17:43:08 2011] [warn] module passenger_module is already loaded, skipping
[Fri Jul 29 17:43:08 2011] [warn] module ssl_module is already loaded, skipping
[Fri Jul 29 17:43:08 2011] [notice] Digest: generating secret for digest authentication ...
[Fri Jul 29 17:43:08 2011] [notice] Digest: done
[Fri Jul 29 17:43:08 2011] [notice] Apache/2.2.3 (CentOS) configured -- resuming normal operations

[root@puppetmaster httpd]# service httpd stop
Stopping httpd:                                            [  OK  ]

[root@puppetmaster httpd]# > /var/log/httpd/error_log 

[root@puppetmaster httpd]# rpm -e rubygem-passenger rubygem-passenger-native-libs rubygem-passenger-native mod_passenger

[root@puppetmaster httpd]# VERS=3.0.7-4.el5

[root@puppetmaster httpd]# yum -y -q install rubygem-passenger-${VERS} mod_passenger-${VERS} rubygem-passenger-native-${VERS} rubygem-passenger-native-libs-${VERS}_1.8.5

[root@puppetmaster httpd]# rpm -qa | grep passenger
rubygem-passenger-native-3.0.7-4.el5
rubygem-passenger-native-libs-3.0.7-4.el5_1.8.5
passenger-release-3-5.el5
rubygem-passenger-3.0.7-4.el5
mod_passenger-3.0.7-4.el5

[root@puppetmaster httpd]# service httpd start
Starting httpd: [Fri Jul 29 17:46:01 2011] [warn] module passenger_module is already loaded, skipping
[Fri Jul 29 17:46:01 2011] [warn] module ssl_module is already loaded, skipping
                                                           [  OK  ]
[root@puppetmaster httpd]# Current thread (1) backtrace:
    #0  0x00002b5e13551fc5 in waitpid () from /lib64/libc.so.6
    No symbol table info available.
    #1  0x00002b5e134f4331 in do_system () from /lib64/libc.so.6
    No symbol table info available.
    #2  0x00000000004eabbe in Passenger::abortHandler(int, siginfo*, void*) ()
    No symbol table info available.
    #3  <signal handler called>
    No symbol table info available.
    #4  0x00002b5e12b17914 in context_new () from /lib64/libselinux.so.1
    No symbol table info available.
    #5  0x00000000004cdc45 in Passenger::SpawnManager::restartServer() ()
    No symbol table info available.
    #6  0x00000000004ce977 in Passenger::SpawnManager::SpawnManager(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::ServerInstanceDir::Generation> const&, boost::shared_ptr<Passenger::AccountsDatabase> const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::AnalyticsLogger> const&, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    No symbol table info available.
    #7  0x00000000004ddb90 in Passenger::ApplicationPool::Pool::Pool(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::ServerInstanceDir::Generation> const&, boost::shared_ptr<Passenger::AccountsDatabase> const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::AnalyticsLogger> const&, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    No symbol table info available.
    #8  0x00000000004df30e in Server::Server(Passenger::FileDescriptor, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int, unsigned int, unsigned int, Passenger::VariantMap const&)
        ()
    No symbol table info available.
    #9  0x0000000000481e6e in main ()
    No symbol table info available.

All thread backtraces:
    Thread 1 (Thread 0x2b5e13c5b210 (LWP 9460)):
    #0  0x00002b5e13551fc5 in waitpid () from /lib64/libc.so.6
    No symbol table info available.
    #1  0x00002b5e134f4331 in do_system () from /lib64/libc.so.6
    No symbol table info available.
    #2  0x00000000004eabbe in Passenger::abortHandler(int, siginfo*, void*) ()
    No symbol table info available.
    #3  <signal handler called>
    No symbol table info available.
    #4  0x00002b5e12b17914 in context_new () from /lib64/libselinux.so.1
    No symbol table info available.
    #5  0x00000000004cdc45 in Passenger::SpawnManager::restartServer() ()
    No symbol table info available.
    #6  0x00000000004ce977 in Passenger::SpawnManager::SpawnManager(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::ServerInstanceDir::Generation> const&, boost::shared_ptr<Passenger::AccountsDatabase> const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::AnalyticsLogger> const&, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    No symbol table info available.
    #7  0x00000000004ddb90 in Passenger::ApplicationPool::Pool::Pool(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::ServerInstanceDir::Generation> const&, boost::shared_ptr<Passenger::AccountsDatabase> const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::AnalyticsLogger> const&, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    No symbol table info available.
    #8  0x00000000004df30e in Server::Server(Passenger::FileDescriptor, int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int, unsigned int, unsigned int, Passenger::VariantMap const&)
        ()
    No symbol table info available.
    #9  0x0000000000481e6e in main ()
    No symbol table info available.

[root@puppetmaster httpd]# cat /var/log/httpd/error_log 
[Fri Jul 29 17:46:01 2011] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[ pid=9460, timestamp=1311954361 ] Process aborted! signo=SIGSEGV(11), reason=SEGV_MAPERR, backtrace available.
--------------------------------------
[ pid=9460 ] Backtrace with 10 frames:
PassengerHelperAgent[0x4eaa45]
/lib64/libpthread.so.0[0x2b5e12901b10]
/lib64/libselinux.so.1(context_new+0x84)[0x2b5e12b17914]
PassengerHelperAgent(_ZN9Passenger12SpawnManager13restartServerEv+0xb73)[0x4cdc45]
PassengerHelperAgent(_ZN9Passenger12SpawnManagerC1ERKSsRKN5boost10shared_ptrINS_17ServerInstanceDir10GenerationEEERKNS4_INS_16AccountsDatabaseEEES2_RKNS4_INS_15AnalyticsLoggerEEEiS2_+0x19f)[0x4ce977]
PassengerHelperAgent(_ZN9Passenger15ApplicationPool4PoolC1ERKSsRKN5boost10shared_ptrINS_17ServerInstanceDir10GenerationEEERKNS5_INS_16AccountsDatabaseEEES3_RKNS5_INS_15AnalyticsLoggerEEEiS3_+0x258)[0x4ddb90]
PassengerHelperAgent(_ZN6ServerC1EN9Passenger14FileDescriptorEiRKSsbS3_S3_S3_S3_jjjjRKNS0_10VariantMapE+0xbba)[0x4df30e]
PassengerHelperAgent(main+0x866)[0x481e6e]
/lib64/libc.so.6(__libc_start_main+0xf4)[0x2b5e134d5994]
PassengerHelperAgent(__gxx_personality_v0+0x1e9)[0x481429]
--------------------------------------
[ pid=9460 ] Dumping a more detailed backtrace with crash-watch ('gem install crash-watch' if you don't have it)...
[Fri Jul 29 17:46:01 2011] [warn] module passenger_module is already loaded, skipping
[Fri Jul 29 17:46:01 2011] [warn] module ssl_module is already loaded, skipping
[Fri Jul 29 17:46:01 2011] [notice] Digest: generating secret for digest authentication ...
[Fri Jul 29 17:46:01 2011] [notice] Digest: done
[ pid=9480, timestamp=1311954361 ] Process aborted! signo=SIGSEGV(11), reason=SEGV_MAPERR, backtrace available.
--------------------------------------
[ pid=9480 ] Backtrace with 10 frames:
PassengerHelperAgent[0x4eaa45]
/lib64/libpthread.so.0[0x2b497a5f6b10]
/lib64/libselinux.so.1(context_new+0x84)[0x2b497a80c914]
PassengerHelperAgent(_ZN9Passenger12SpawnManager13restartServerEv+0xb73)[0x4cdc45]
PassengerHelperAgent(_ZN9Passenger12SpawnManagerC1ERKSsRKN5boost10shared_ptrINS_17ServerInstanceDir10GenerationEEERKNS4_INS_16AccountsDatabaseEEES2_RKNS4_INS_15AnalyticsLoggerEEEiS2_+0x19f)[0x4ce977]
PassengerHelperAgent(_ZN9Passenger15ApplicationPool4PoolC1ERKSsRKN5boost10shared_ptrINS_17ServerInstanceDir10GenerationEEERKNS5_INS_16AccountsDatabaseEEES3_RKNS5_INS_15AnalyticsLoggerEEEiS3_+0x258)[0x4ddb90]
PassengerHelperAgent(_ZN6ServerC1EN9Passenger14FileDescriptorEiRKSsbS3_S3_S3_S3_jjjjRKNS0_10VariantMapE+0xbba)[0x4df30e]
PassengerHelperAgent(main+0x866)[0x481e6e]
/lib64/libc.so.6(__libc_start_main+0xf4)[0x2b497b1ca994]
PassengerHelperAgent(__gxx_personality_v0+0x1e9)[0x481429]
--------------------------------------
[ pid=9480 ] Dumping a more detailed backtrace with crash-watch ('gem install crash-watch' if you don't have it)...
[Fri Jul 29 17:46:01 2011] [notice] Apache/2.2.3 (CentOS) configured -- resuming normal operations

[root@puppetmaster httpd]# ps -ef | grep -i Passenger
root      9475  9473  0 17:46 ?        00:00:00 PassengerWatchdog
root      9478  9475  0 17:46 ?        00:00:00 PassengerHelperAgent
root      9480  9478  0 17:46 ?        00:00:00 [PassengerHelper] <defunct>
nobody    9487  9475  0 17:46 ?        00:00:00 PassengerLoggingAgent
root      9515  2678  0 17:48 pts/0    00:00:00 grep -i passenger

</pre>

**Comment by ghost** [comment]
I get the exact same results when using the 3.0.7-4 rpms. Using the gems via gem install passenger works just fine.

**Comment by erikogan** [comment]
Thank you for the great feedback, I only have one question: what is the SELinux enforcement configuration on the box? (Enforcing, permissive, disabled), and if one of the first two, which policy (targeted, strict, or your own?)

A segfault is unlikely to be caused by SELinux, but I’ve spent a lot of time chasing down strange interactions that ended up being caused by (or at least rooted in) SELinux.

Unfortunately, this problem is not quite as simple as it first appears. Because of the collaboration that was going on, many of the earlier versions were built from tarballs generated from git, rather than the official release of Passenger. With 3.0.7-4 I finally fixed that once and for all, because it never sat well with me that we weren’t building from “pristine sources.”

So 3.0.7-2 has fixes from the upstream git repository that aren’t in 3.0.7, and it’s entirely possible that they fixed the segfault and it’ll be incorporated into 3.0.8. I’m going to try to reproduce your problem on a CentOS 5 VM, and look through the commits to see if anything strikes me as a likely culprit. 

Once we track it down, I’ll add it as a patch, so we’re still building with pristine sources

**Comment by erikogan** [comment]
khightower: It is also interesting that building via the gem route works fine. I assume that you end up with 3.0.7 installed?

**Comment by willaerk** [comment]
erikogan: thanks for the swift response. I have disabled SELinux. So that can probably be ruled out.

I'll try to spend some time tracking down the right patch myself.

**Comment by erikogan** [comment]
I’ve tracked it down. The problem is caused by the patch I added to make PassengerAgentHelper SELinux aware enough to request a domain transition when it exec's ruby. It doesn't correctly handle itself when SELinux is completely disabled. 

I don't yet have a fix (I have been fighting with my build VM, this being the first time I've turned it on since updating to Lion) but I should have one fairly soon.

**Comment by ghost** [comment]
I am glad you tracked this down. I can help with testing when you are done.

**Comment by erikogan** [comment]
The latest commits to the tree now fix this problem. I’m in the middle of rebuilding the packages one last time to resolve a minorly annoying dependency problem. Once that’s done I’ll rsync them out to the main repository. (Mirrors should pick them up in a few hours after that.)

Thanks for your patience!

**Comment by erikogan** [comment]
There was a small snafu with the script that automatically promotes a release. 3.0.7-5 RPMs are now on the main repository, and should be picked up by the mirrors soon. 

A “yum update” should upgrade you to the latest packages, which should resolve the segfault.

Please let me know if you have any other problems.

**Comment by willaerk** [comment]
I can confirm the updated package works for me.
Thanks a bunch for the swift justice !
