### ISSUE TITLE
Dependency problem: libev

### ISSUE THREAD

**Issue by incase** [erikogan/passenger#12]
Hi. 

You compiled your RPMs for RHEL6 against  libev.so.3, however the only RPMs of libev I could find are those in EPEL, and EPEL currently only carries libev-4.0.3-2.el5 (libev.so.4). So I think you either need to re-compile after updating libev, or you need to specify which repository we could use to fetch libev.so.3 from.

Kind regards

**Comment by incase** [comment]
Damn it, forget about that. I happened to have the wrong EPEL repository configured on my CentOS6 system: I referenced the RHEL/CentOS5 version of the Repository instead, which - curiously - has a more recent version of libev than the RHEL6/CentOS6 version of the repo.

**Comment by erikogan** [comment]
That IS curious. I did some research on my CentOS 6 box this morning and found the libev-3.x via EPEL, and was puzzled by your bug report. I was just now getting back to figuring out what might be going on, and noticed your update. I'm glad you were able to resolve it.

But now I'm curious why the version discrepancy…

**Comment by ekohl** [comment]
I don't have permission to re-open this, but it appears libev 4 made it to EPEL-6 as well. This causes a dependency issue as described above.

If we check http://koji.fedoraproject.org/koji/buildinfo?buildID=253112 you'd think that since mid July there was only version 4 available so it's odd that on August 2nd it did work. I think that when I installed a machine 2 or 3 weeks ago it worked as well, but now it doesn't.

**Comment by erikogan** [comment]
When I looked on 8/2 there was definitely only libev-3. I’ve reopened the issue until we can track down what’s actually going on and find a fix.

**Comment by erikogan** [comment]
There are now libev-4 packages available in EPEL. It's strange that they'd change major versions like that, but I suspect it was an accident that libev-3 was included in the first place.

I'm building 3.0.8-2 for EL6 now, and it will be available soon.

**Comment by erikogan** [comment]
3.0.8-2 for EL6 is now available, with updated libev dependencies. Please let me know if you have any problems with them.

Thanks!

**Comment by ekohl** [comment]
It appears the repo data hasn't been updated so yum doesn't know about the new packages.

**Comment by erikogan** [comment]
That's strange. I’m certain that I updated the repo data before swapping in the new repository. In any case, it’s definitely fixed now, I just tested it. Sorry for the problems.

(If your fastest mirrors cache list the mirror it may take a few hours for that to update. Clearing that information out should pull from the primary repository)

**Comment by ekohl** [comment]
I can confirm it works for me. Thanks for the fast response :)
