### ISSUE TITLE
Apache PassengerTempDir should be set to /var/run/passenger

### ISSUE THREAD

**Issue by erikogan** [erikogan/passenger#13]
SELinux dislikes us writing to /tmp. I believe I have fixed this in the SELinux policy module, however investigate if this is a better solution.

**Comment by opoplawski** [comment]
Yeah, /tmp is actually a bad place to put things.

**Comment by erikogan** [comment]
This was fixed in 3.0.9-1

**Comment by opoplawski** [comment]
On 09/07/2011 11:13 PM, Erik Ogan wrote:

> This was fixed in 3.0.9-1

Looks good.  Thanks!

## 

Orion Poplawski
Technical Manager                     303-415-9701 x222
NWRA/CoRA Division                    FAX: 303-415-9702
3380 Mitchell Lane                  orion@cora.nwra.com
Boulder, CO 80301              http://www.cora.nwra.com
