### ISSUE TITLE
404 error when trying to execute `yum install mod_passenger`

### ISSUE THREAD

**Issue by linusthe3rd** [erikogan/passenger#15]
After setting up the passenger yum repo on RHEL 6 and executing `yum install mod_passenger` I get the following error:

```
http://passenger.stealthymonkeys.com/rhel/6Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 : http://passenger.stealthymonkeys.com/rhel/6Server/x86_64/repodata/repomd.xml 

Error: Cannot retrieve repository metadata (repomd.xml) for repository: passenger. Please verify its path and try again
```

This URI does not point to an actual file on that server, the correct URI should be:

`http://passenger.stealthymonkeys.com/rhel/6/x86_64/repodata/repomd.xml`

**Comment by erikogan** [comment]
Hi, you appear to be the first person using the packages on RHEL proper, as opposed to one of the rebuild distributions.

The yum repository configuration file uses the $releasever variable. On CentOS that is set to "6," and on RHEL it's set to "6Server." I've added a symlink on the repository so they both should work. Let me know if you have any further trouble. Thanks!
