### ISSUE TITLE
add HMDC repository to mirrorlist

### ISSUE THREAD

**Issue by hakamadare** [erikogan/passenger#2]
hi Erik!

i notice that [HMDC's mirror](http://mirror.hmdc.harvard.edu/mirrors/passenger) isn't listed in [http://passenger.stealthymonkeys.com/rhel/mirrors]() or [http://passenger.stealthymonkeys.com/fedora/mirrors]().  i don't mean to pester you, but you might want to list our mirror in order to divert some load from your main repo. :)

-Steve

**Comment by erikogan** [comment]
Sorry for the delay, I just got back from traveling that was a break after the 100+ hr/week marathon that I'd been on.

I thought I'd already done this, so let me see what went wrong. :)

-e

**Comment by erikogan** [comment]
I checked in the changes to the base mirrors file, but never ran the script to recreate the files (with the appropriate suffix) for the public repository.

Fixed!
