### ISSUE TITLE
Dependency issues with EL6.2 ruby update

### ISSUE THREAD

**Issue by opoplawski** [erikogan/passenger#20]
# yum -y upgrade

Loaded plugins: auto-update-debuginfo, downloadonly, priorities
1134 packages excluded due to repository priority protections
Setting up Upgrade Process
Resolving Dependencies
--> Running transaction check
---> Package ruby.x86_64 0:1.8.7.299-7.el6_1.1 will be updated
--> Processing Dependency: ruby = 1.8.7.299 for package: 1:rubygem-passenger-native-libs-3.0.11-1.el6_1.8.7.299.x86_64
---> Package ruby.x86_64 0:1.8.7.352-3.el6 will be an update
---> Package ruby-devel.x86_64 0:1.8.7.299-7.el6_1.1 will be updated
---> Package ruby-devel.x86_64 0:1.8.7.352-3.el6 will be an update
---> Package ruby-irb.x86_64 0:1.8.7.299-7.el6_1.1 will be updated
---> Package ruby-irb.x86_64 0:1.8.7.352-3.el6 will be an update
---> Package ruby-libs.x86_64 0:1.8.7.299-7.el6_1.1 will be updated
---> Package ruby-libs.x86_64 0:1.8.7.352-3.el6 will be an update
---> Package ruby-rdoc.x86_64 0:1.8.7.299-7.el6_1.1 will be updated
---> Package ruby-rdoc.x86_64 0:1.8.7.352-3.el6 will be an update
--> Finished Dependency Resolution
Error: Package: 1:rubygem-passenger-native-libs-3.0.11-1.el6_1.8.7.299.x86_64 (@passenger)
           Requires: ruby = 1.8.7.299
           Removing: ruby-1.8.7.299-7.el6_1.1.x86_64 (@sl-security)
               ruby = 1.8.7.299-7.el6_1.1
           Updated By: ruby-1.8.7.352-3.el6.x86_64 (sl-security)
               ruby = 1.8.7.352-3.el6
           Available: ruby-1.8.7.299-7.el6.x86_64 (sl)
               ruby = 1.8.7.299-7.el6

Now, does rubygem-passenger-native-libs-3.0.11-1.el6_1.8.7.299.x86_64 really need to depend so explicitly on the ruby version?

**Comment by erikogan** [comment]
Unfortunately, yes it does. The native-libs package has to match the patch-level of the installed Ruby interpreter, or it can lead to instability.

Sorry, I'm working from CentOS packages, which lag behind RHEL just a bit. I've grabbed the SRPM from 6.2 and I'll try to get the packages out this morning.

Incidentally, it's possible to use the passenger SRPM to build native-libs packages alone (so that it's easier to swap out the ruby interpreter), but it's not well documented. I'll probably use this as an opportunity to fix that.

**Comment by erikogan** [comment]
The x86_64 rubygem-passenger-native-libs-3.0.11-1.el6_1.8.7.352 package is now available on the repository. I'll keep this issue open until I build i686 packages, 

…Those will take a bit longer because I cleaned up my i686 VM when I was finally able to buld EL6 packages with mock.

**Comment by erikogan** [comment]
The i686 rubygem-passenger-native-libs-3.0.11-1.el6_1.8.7.352 package is now available on the repository.

Thanks for the heads-up on this!

**Comment by opoplawski** [comment]
On 12/10/2011 03:15 PM, Erik Ogan wrote:

> The i686 rubygem-passenger-native-libs-3.0.11-1.el6_1.8.7.352 package is now available on the repository.
> 
> Thanks for the heads-up on this!

Looks good, thanks!

## 

Orion Poplawski
Technical Manager                     303-415-9701 x222
NWRA/CoRA Division                    FAX: 303-415-9702
3380 Mitchell Lane                  orion@cora.nwra.com
Boulder, CO 80301              http://www.cora.nwra.com
