### ISSUE TITLE
fedora ruby update breaks native-libs dep

### ISSUE THREAD

**Issue by mwichmann** [erikogan/passenger#22]
Perhaps simplest to just paste.  Summary: rubygem-passenger-native-libs needs a respin, even though the ruby bump is small (.352 to .357).  This one is for f16, same situation on f15:

--> Running transaction check
---> Package ruby.x86_64 0:1.8.7.352-1.fc16 will be updated
--> Processing Dependency: ruby = 1.8.7.352 for package: 1:rubygem-passenger-native-libs-3.0.11-1.fc16_1.8.7.352.x86_64
---> Package ruby.x86_64 0:1.8.7.357-1.fc16 will be an update
---> Package ruby-devel.x86_64 0:1.8.7.352-1.fc16 will be updated
---> Package ruby-devel.x86_64 0:1.8.7.357-1.fc16 will be an update
---> Package ruby-irb.noarch 0:1.8.7.352-1.fc16 will be updated
---> Package ruby-irb.noarch 0:1.8.7.357-1.fc16 will be an update
---> Package ruby-libs.x86_64 0:1.8.7.352-1.fc16 will be updated
---> Package ruby-libs.x86_64 0:1.8.7.357-1.fc16 will be an update
---> Package ruby-rdoc.noarch 0:1.8.7.352-1.fc16 will be updated
---> Package ruby-rdoc.noarch 0:1.8.7.357-1.fc16 will be an update
--> Finished Dependency Resolution
Error: Package: 1:rubygem-passenger-native-libs-3.0.11-1.fc16_1.8.7.352.x86_64 (@passenger)
           Requires: ruby = 1.8.7.352
           Removing: ruby-1.8.7.352-1.fc16.x86_64 (@anaconda-0)
               ruby = 1.8.7.352-1.fc16
           Updated By: ruby-1.8.7.357-1.fc16.x86_64 (updates)
               ruby = 1.8.7.357-1.fc16

**Comment by erikogan** [comment]
Thanks for the heads up! I’m spinning up the build for those packages now. (And also finally exposing building them in a rake task. Right now you’d have to invoke the script yourself.)

**Comment by erikogan** [comment]
These packages are now available on the main repository. 

If you tried to update packages within the last 6 hours, you may need to clear the metadata cache for the repository to force yum to download it again:
% yum clean metadata --disablerepo=\\* --enablerepo=passenger

Thanks!

**Comment by mwichmann** [comment]
That was quick!  Worked fine here, thanks.
