### ISSUE TITLE
http://passenger.stealthymonkeys.com/rhel/5Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by sberryman** [erikogan/passenger#23]
It looks like it is pointing to a directory that doesn't exist. 

http://passenger.stealthymonkeys.com/rhel/
only contains:
5, 6.0, 6.1, 6, 6rolling and 6Server. There is no 5Server folder.

I tried the following:
[XXX@XXX ~]# sudo rpm -Uvh http://passenger.stealthymonkeys.com/rhel/5/passenger-release.noarch.rpm
Retrieving http://passenger.stealthymonkeys.com/rhel/5/passenger-release.noarch.rpm
warning: /var/tmp/rpm-xfer.K6yv2l: Header V4 DSA signature: NOKEY, key ID 71e042e4
Preparing...                ########################################### [100%]
   1:passenger-release      ########################################### [100%]
[XXX@XXX ~]# sudo yum update
Loaded plugins: rhnplugin, security
http://passenger.stealthymonkeys.com/rhel/5Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
http://passenger.stealthymonkeys.com/rhel/5Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
http://mirror.hmdc.harvard.edu/mirrors/passenger/rhel/5Server/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: passenger. Please verify its path and try again

**Comment by erikogan** [comment]
The problem here is that ScientificLinux uses a non-standard directory structure.

This has been reported before, and I added a script to my deploy process that peeks at the directories on the SL FTP server and symlinks appropriately.

I’ll add a symlink now, and investigate why the script no longer works for the 5.\* series.

**Comment by erikogan** [comment]
ScientificLinux’s own FTP server no longer contains 5Server or 6Server. I should look at their yum repo packages and see how they’re referencing the directory (though it looks to be different than RHEL & CentOS, so I probably won’t be able to use it)

In the mean time I’ve added symlinks so things should be working for SL again. Thanks.

Sorry for the delay.

**Comment by sberryman** [comment]
Thanks for adding the symlinks
